remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme
title: [phpBB Auto Groups Extension]
description: [Documentation for extension developers looking to create add-ons for Auto Groups or to integrate Auto Groups functionality with their own extensions.]
